import { Link } from 'react-router-dom'
import {
  Scale,
  FileText,
  Users,
  CreditCard,
  AlertTriangle,
  Shield,
  Calendar,
  Mail,
  ArrowRight,
} from 'lucide-react'

type Section = {
  id: string
  title: string
  icon: React.FC<{ className?: string }>
  content: {
    subtitle: string
    text: string
  }[]
}

const sections: Section[] = [
  {
    id: 'acceptance',
    title: 'Acceptance of Terms',
    icon: Scale,
    content: [
      {
        subtitle: 'Agreement to Terms',
        text:
          'By accessing and using WordWise AI, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.',
      },
      {
        subtitle: 'Changes to Terms',
        text:
          'We reserve the right to change these terms at any time. Your continued use of WordWise AI following any changes indicates your acceptance of the new terms.',
      },
    ],
  },
  {
    id: 'service-description',
    title: 'Service Description',
    icon: FileText,
    content: [
      {
        subtitle: 'AI Writing Assistant',
        text:
          'WordWise AI provides artificial intelligence-powered writing assistance, including grammar checking, style suggestions, clarity improvements, and engagement enhancements.',
      },
      {
        subtitle: 'Service Availability',
        text:
          'We strive to maintain high service availability, but we do not guarantee uninterrupted access. We may temporarily suspend service for maintenance or updates.',
      },
      {
        subtitle: 'Feature Updates',
        text:
          'We continuously improve our service and may add, modify, or remove features. We will notify users of significant changes that affect functionality.',
      },
    ],
  },
  {
    id: 'user-responsibilities',
    title: 'User Responsibilities',
    icon: Users,
    content: [
      {
        subtitle: 'Account Security',
        text:
          'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account.',
      },
      {
        subtitle: 'Appropriate Use',
        text:
          'You agree to use WordWise AI only for lawful purposes and in accordance with these terms. You will not use the service to create harmful, offensive, or illegal content.',
      },
      {
        subtitle: 'Content Ownership',
        text:
          'You retain ownership of all content you create using WordWise AI. However, you grant us a license to process your content to provide our services.',
      },
    ],
  },
  {
    id: 'payment-terms',
    title: 'Payment and Billing',
    icon: CreditCard,
    content: [
      {
        subtitle: 'Subscription Plans',
        text:
          'WordWise AI offers both free and premium subscription plans. Premium features require a paid subscription with billing cycles as specified in your plan.',
      },
      {
        subtitle: 'Payment Processing',
        text:
          'Payments are processed securely through third-party payment processors. We do not store your complete payment information on our servers.',
      },
      {
        subtitle: 'Refund Policy',
        text:
          'Refunds are available within 30 days of purchase for annual subscriptions. Monthly subscriptions are non-refundable but can be cancelled at any time.',
      },
    ],
  },
  {
    id: 'limitations',
    title: 'Limitations and Disclaimers',
    icon: AlertTriangle,
    content: [
      {
        subtitle: 'Service Limitations',
        text:
          "While we strive for accuracy, WordWise AI's suggestions are generated by artificial intelligence and may not always be perfect. Users should review all suggestions before accepting them.",
      },
      {
        subtitle: 'Liability Limitation',
        text:
          'Our liability is limited to the amount you paid for the service in the 12 months preceding any claim. We are not liable for indirect, incidental, or consequential damages.',
      },
      {
        subtitle: 'No Warranty',
        text:
          "The service is provided 'as is' without warranties of any kind, either express or implied, including but not limited to warranties of merchantability or fitness for a particular purpose.",
      },
    ],
  },
  {
    id: 'termination',
    title: 'Termination',
    icon: Shield,
    content: [
      {
        subtitle: 'Account Termination',
        text:
          'You may terminate your account at any time by contacting our support team. We may terminate accounts that violate these terms or engage in harmful activities.',
      },
      {
        subtitle: 'Data Retention',
        text:
          'Upon termination, we will retain your data for a reasonable period to allow for account recovery, after which it will be permanently deleted.',
      },
      {
        subtitle: 'Survival of Terms',
        text:
          'Certain provisions of these terms will survive termination, including intellectual property rights, limitation of liability, and dispute resolution.',
      },
    ],
  },
]

export function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100">
      {/* Header */}
      <header className="border-b border-white/20 backdrop-blur-sm bg-white/80 sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center space-x-2">
            <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
              <Scale className="w-5 h-5 text-white" />
            </div>
            <span className="text-xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              WordWise AI
            </span>
          </Link>
          <Link to="/" className="inline-flex items-center text-gray-700 hover:text-gray-900 transition-colors text-sm">
            Back to Home
          </Link>
        </div>
      </header>

      <div className="container mx-auto px-4 py-12">
        {/* Hero */}
        <div className="text-center mb-12 max-w-3xl mx-auto">
          <div className="inline-flex items-center px-3 py-1 mb-6 bg-purple-100 text-purple-700 rounded-full text-sm font-medium">
            <Scale className="w-4 h-4 mr-2" /> Legal Terms
          </div>
          <h1 className="text-4xl md:text-5xl font-bold mb-6 bg-gradient-to-r from-gray-900 via-blue-800 to-purple-800 bg-clip-text text-transparent">
            Terms of Service
          </h1>
          <p className="text-lg text-gray-600 leading-relaxed">
            These terms govern your use of WordWise AI. Please read them carefully as they contain important information
            about your rights and obligations.
          </p>
          <div className="flex items-center justify-center mt-6 text-sm text-gray-500">
            <Calendar className="w-4 h-4 mr-2" /> Last updated: December 21, 2024
          </div>
        </div>

        {/* Quick Navigation */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4 mb-10">
          {sections.map((section) => (
            <a
              key={section.id}
              href={`#${section.id}`}
              className="flex items-center p-4 rounded-lg border border-gray-200 hover:border-purple-300 hover:bg-purple-50 transition-colors"
            >
              <section.icon className="w-5 h-5 text-purple-600 mr-3" />
              <span className="text-sm font-medium text-gray-700">{section.title}</span>
            </a>
          ))}
        </div>

        {/* Sections */}
        <div className="space-y-12">
          {sections.map((section) => (
            <section key={section.id} id={section.id} className="bg-white/80 backdrop-blur-sm border-0 shadow-lg rounded-lg p-8">
              <div className="flex items-center mb-6 space-x-4">
                <div className="w-12 h-12 bg-gradient-to-r from-purple-500 to-blue-500 rounded-xl flex items-center justify-center">
                  <section.icon className="w-6 h-6 text-white" />
                </div>
                <h2 className="text-2xl font-bold text-gray-900">{section.title}</h2>
              </div>
              <div className="space-y-8">
                {section.content.map((item, idx) => (
                  <div key={idx} className="space-y-3">
                    <h3 className="text-lg font-semibold text-gray-900">{item.subtitle}</h3>
                    <p className="text-gray-600 leading-relaxed">{item.text}</p>
                  </div>
                ))}
              </div>
            </section>
          ))}
        </div>

        {/* Contact CTA */}
        <div className="mt-16 bg-gradient-to-r from-purple-600 to-blue-600 text-white rounded-lg p-10 text-center shadow-lg">
          <h2 className="text-2xl font-bold mb-4">Questions About Our Terms?</h2>
          <p className="text-lg mb-6 opacity-90">
            If you have any questions about these Terms of Service, please contact our legal team.
          </p>
          <Link
            to="/contact"
            className="inline-flex items-center px-6 py-3 bg-white text-purple-600 rounded-md hover:bg-gray-100 transition-colors"
          >
            <Mail className="w-5 h-5 mr-2" /> Contact Legal Team <ArrowRight className="w-5 h-5 ml-2" />
          </Link>
        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-gray-200 bg-white mt-16">
        <div className="container mx-auto px-4 py-8 flex flex-col md:flex-row justify-between items-center text-sm text-gray-600">
          <div className="flex items-center space-x-2 mb-4 md:mb-0">
            <div className="w-6 h-6 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
              <Scale className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
              WordWise AI
            </span>
          </div>
          <div className="flex space-x-6">
            <Link to="/privacy" className="hover:text-gray-900">
              Privacy
            </Link>
            <Link to="/terms" className="hover:text-gray-900 font-medium">
              Terms
            </Link>
            <Link to="/contact" className="hover:text-gray-900">
              Contact
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
} 